### ISSUE TITLE
Script para Deploy

### ISSUE THREAD

**Issue by diogoleal** [area31/Podcast#7]
Criar script para deploy do site.

**Comment by diogoleal** [comment]
@coffnix,
Pensando bem, acho que não precisamos de um script de deploy, isso pode ser rodado via crontab.

Instale o ```python-virtualenv,  virtualenvwrapper e git```
```
git clone https://github.com/area31/Podcast.git
mkvirtualenv podcast
cd Podcast
pip install -r requirements.txt
```
Então tu pode colocar na crontab:
```
cd podcast 
workon podcast 
git pull || make html || cp -rf output /var/www/podcast/
```

**Comment by coffnix** [comment]
Perfeito! Assim que a edição concluir fazemos dessa forma via cron. :D
